### ISSUE TITLE
フロントエンド: Remixでのi18nの調査と検証

### ISSUE THREAD

**Issue by yu23ki14** [hackdays-io/toban#195]
# i18n

## Description

- 海外プロジェクトとの連携や、導入も早めに進めたいので、言語対応を日本語・英語の両方にしたい
- Remixでのi18nについて調べて、ミニマムでセットアップしてみる

**Comment by mashharuki** [comment]
参考になりそうなブログ記事を発見！！

https://note.com/lizefield/n/naa3fb014a8c9

**Comment by mashharuki** [comment]
https://remix.run/blog/remix-i18n

https://zenn.dev/mktu/articles/7f924edd8125a4

**Comment by mashharuki** [comment]
https://github.com/sergiodxa/remix-i18next
↑ GitHub 基本的にこの内容通りに設定を進めれば良さそう！

**Comment by mashharuki** [comment]
<img width="1102" alt="スクリーンショット 2024-12-09 20 59 19" src="https://github.com/user-attachments/assets/5145641e-f8ca-4205-aaad-9c4e4e41dfd3">
↑ ビルドは通った！！

**Comment by mashharuki** [comment]
<img width="1728" alt="スクリーンショット 2024-12-09 21 00 33" src="https://github.com/user-attachments/assets/5d47e2a6-e9ab-402c-a259-6494aa008547">

**Comment by mashharuki** [comment]
↑ と思ったらエラーになった・・・。

**Comment by mashharuki** [comment]
エラー内容

```txt
(node:20938) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [ReadStream]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
9:44:01 PM [vite] server restarted.
9:44:08 PM [vite] Internal server error: Cannot read properties of undefined (reading 'status')
      at Object.toNodeRequest (/Users/harukikondo/git/toban/node_modules/@remix-run/dev/dist/vite/node-adapter.js:69:28)
      at nodeHandler (/Users/harukikondo/git/toban/node_modules/@remix-run/dev/dist/vite/plugin.js:869:35)
      at /Users/harukikondo/git/toban/node_modules/@remix-run/dev/dist/vite/plugin.js:871:15
✘ [ERROR] Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)

    ../../node_modules/i18next-fs-backend/esm/readFile.js:8:20:
      8 │ var fs = !isDeno ? (await import('node:fs')).default : undefined;
        ╵                     ~~~~~

✘ [ERROR] Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)

    ../../node_modules/i18next-fs-backend/esm/writeFile.js:7:20:
      7 │ var fs = !isDeno ? (await import('node:fs')).default : undefined;
        ╵                     ~~~~~

9:44:08 PM [vite] error while updating dependencies:
Error: Build failed with 2 errors:
../../node_modules/i18next-fs-backend/esm/readFile.js:8:20: ERROR: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)
../../node_modules/i18next-fs-backend/esm/writeFile.js:7:20: ERROR: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)
    at failureErrorWithLog (/Users/harukikondo/git/toban/node_modules/vite/node_modules/esbuild/lib/main.js:1472:15)
    at /Users/harukikondo/git/toban/node_modules/vite/node_modules/esbuild/lib/main.js:945:25
    at /Users/harukikondo/git/toban/node_modules/vite/node_modules/esbuild/lib/main.js:1353:9
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Comment by mashharuki** [comment]
デモサイト見つけた！
これを参考にする。

https://remix-i18n.fly.dev/?lng=ja

コードは以下の通り
https://github.com/dev-xo/remix-i18n-example?tab=readme-ov-file

**Comment by mashharuki** [comment]
https://sergiodxa.com/tutorials/add-i18n-to-a-remix-vite-app
↑ とりあえずこれで検証してみる。

**Comment by mashharuki** [comment]
https://github.com/mashharuki/remix-vite-i18next
↑ これで最小構成の検証が完了。

これが移植できれば良さそう。

**Comment by mashharuki** [comment]
一旦pending
