### ISSUE TITLE
Contract: BigBang関数を用意して、プロジェクト作成時の3つの署名プロセスを省略する

### ISSUE THREAD

**Issue by ikmzkro** [hackdays-io/toban#73]
## ASIS
- プロジェクト作成時に下記３つの署名プロセスが存在するためUIUX品質を下げている
- プロジェクト作成後の役割処理のテストが停滞する

1. const bigbang1 = await resTopHatMint.writeAsync();
2. const bigbang2 = await resHatterHatMint.writeAsync();
3. const bigbang3 = await resHatMint.writeAsync();

## TOBE
1つの署名で上記３TXを実行する

- 不完全なコントラクトの改修
  - https://github.com/hackdays-io/toban/blob/main/pkgs/contract/contracts/bigbang/MultiClaimsFractionHatter.sol 
- テストコードの実装
- フロントエンドとの繋ぎこみ

**Comment by ikmzkro** [comment]
コントラクト不備により余計なuseHooks、useEffect、署名プロセスが2回多くなっている。

**Comment by ikmzkro** [comment]
HatsTimeFrameModuleのデプロイ（HatsModuleFactory）を書く

**Comment by ikmzkro** [comment]
viem使ったテストコード入門
```
Request Arguments:
  from:  0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  to:    0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9
  data:  0x267adfd100000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb9226600000000000000000000000070997970c51812dc3a010c7d01b50e0d17dc79c8000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002e5468697320697320612062696762616e672066756e6374696f6e20746f2063726561746520612070726f6a656374000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001d68747470733a2f2f6578616d706c652e636f6d2f696d6167652e706e67000000
 
Contract Call:
  address:   0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9
  function:  bigbang(string _details, uint32 _maxSupply, address _eligibility, address _toggle, bool _mutable, string _imageURI, address _trustedForwarder)
  args:             (This is a bigbang function to create a project, 1, 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266, 0x70997970c51812dc3a010c7d01b50e0d17dc79c8, true, https://example.com/image.png, 0x0000000000000000000000000000000000000000)
  sender:    0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266

Docs: https://viem.sh/docs/contract/writeContract
Details: Transaction reverted without a reason string
Version: 2.20.1
      at getContractError (/home/ikmz/toban/node_modules/viem/utils/errors/getContractError.ts:72:10)
      at writeContract (/home/ikmz/toban/node_modules/viem/actions/wallet/writeContract.ts:208:27)
      at async Context.<anonymous> (test/BigBang.ts:49:14)
     Caused by: TransactionExecutionError: An unknown RPC error occurred.
  
  Request Arguments:
    from:  0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
    to:    0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9
    data:  0x267adfd100000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb9226600000000000000000000000070997970c51812dc3a010c7d01b50e0d17dc79c8000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000001400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002e5468697320697320612062696762616e672066756e6374696f6e20746f2063726561746520612070726f6a656374000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001d68747470733a2f2f6578616d706c652e636f6d2f696d6167652e706e67000000
  
  Details: Transaction reverted without a reason string
  Version: 2.20.1
      at getTransactionError (/home/ikmz/toban/node_modules/viem/utils/errors/getTransactionError.ts:44:10)
      at sendTransaction (/home/ikmz/toban/node_modules/viem/actions/wallet/sendTransaction.ts:290:30)
      at async writeContract (/home/ikmz/toban/node_modules/viem/actions/wallet/writeContract.ts:197:12)
      at async Context.<anonymous> (test/BigBang.ts:49:14)
     Caused by: UnknownRpcError: An unknown RPC error occurred.
  
  Details: Transaction reverted without a reason string
  Version: 2.20.1
      at delay.count.count (/home/ikmz/toban/node_modules/viem/utils/buildRequest.ts:186:25)
      at async attemptRetry (/home/ikmz/toban/node_modules/viem/utils/promise/withRetry.ts:44:22)
     Caused by: Error: Transaction reverted without a reason string
      at BigBang.bigbang (contracts/bigbang/BigBang.sol:35)
      at BigBang.bigbang (contracts/bigbang/BigBang.sol:44)
      at EdrProviderWrapper.request (/home/ikmz/toban/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:433:41)
      at async delay.count.count (/home/ikmz/toban/node_modules/viem/utils/buildRequest.ts:118:22)
      at async attemptRetry (/home/ikmz/toban/node_modules/viem/utils/promise/withRetry.ts:44:22)




Your solidity settings have viaIR enabled, which is not fully supported yet. You can still use Hardhat, but some features, like stack traces, might not work correctly.

Learn more at https://hardhat.org/solc-viair
╭───────────────────────────────────────────────────────╮
│                                                       │
│   New Hardhat release available! 2.22.9 -> 2.22.10.   │
│                                                       │
│   Changelog: https://hardhat.org/release/2.22.10      │
│                                                       │
│   Run "npm install hardhat@latest" to update.         │
│                                                       │
╰───────────────────────────────────────────────────────╯
```

**Comment by ikmzkro** [comment]
beforeeach内で`BigBang = _BigBang;`とできないのは、viem.deployContractの返却型と一致していないため。
他関数ではどうなのか👀
